app/forms/talleres_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length

from models.usuarios import Usuario
from models.talleres import Taller

class CrearTaller(FlaskForm):
    nombre = StringField('Nombre del taller', validators=[DataRequired(), Length(min=3, message='Este campo debe contener al menos 3 letras')])
    descrip = TextAreaField('Descripción del taller', validators=[DataRequired(), Length(min=3, message='Este campo debe contener al menos 3 letras')])
    categoria = StringField('Categoria del taller', validators=[DataRequired(), Length(min=3, max=30, message='Este campo debe contener al menos 3 letras')])
    submit = SubmitField('Crear Taller')

class ActualizarTaller(FlaskForm):
    nombre = StringField('Nombre del taller', validators=[DataRequired(), Length(min=3, message='Este campo debe contener al menos 3 letras')])
    descrip = TextAreaField('Descripción del taller', validators=[DataRequired(), Length(min=3, message='Este campo debe contener al menos 3 letras')])
    categoria = StringField('Categoria del taller', validators=[DataRequired(), Length(min=3, max=30, message='Este campo debe contener al menos 3 letras')])
    submit = SubmitField('Guardar Taller')

class BuscarTaller(FlaskForm):
    tipo = SelectField('Buscar por...', coerce=int, choices=[(1, 'Nombre'), (2, 'Categoria')])
    texto = StringField('Busqueda:', validators=[DataRequired(), Length(min=3, message='Este campo debe contener al menos 3 caracteres')])
    submit = SubmitField('Buscar')

app/views/home_views.py
from flask import Blueprint, render_template, abort

from models.talleres import Taller

home_views = Blueprint('home', __name__)

@home_views.route("/")
@home_views.route("/home/")
def home():
    return render_template('home/home.html')

@home_views.route("/home/info_texcalac")
def info_texcalac():
    return render_template('home/infoTexca.html')

@home_views.route("/home/info_talleres")
@home_views.route("/home/info_talleres/<int:page>", methods=['GET'])
def info_talleres(page=1):
    limit = 5
    talleres = Taller.get_all(limit=limit, page=page)
    if talleres is None: abort(404)
    return render_template('home/infotalleres.html', talleres=talleres, page=page)

app/views/users_views.py
from flask import Blueprint, redirect, render_template, url_for, flash, abort, session

from models.usuarios import Usuario, Toma

from models.talleres import Taller, Asignado

from forms.usuarios_forms import LoginForm, RegisterForm, ElegirTaller, OlvideContra, ProfileForm

import datetime
import math


user_views = Blueprint('user', __name__)

@user_views.route("/register/", methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        nombre = form.nombre.data
        aPaterno = form.aPaterno.data
        aMaterno = form.aMaterno.data
        correoE = form.correoE.data
        contrasenia = form.contrasenia.data
        telefono = form.telefono.data
        edad = form.edad.data
        rol = form.rol.data
        fecha_actual = datetime.datetime.now().date()

        user = Usuario(nombre, aPaterno, aMaterno, correoE, contrasenia, telefono, edad, rol, None, fecha_actual)
        user.guardar()
        return redirect(url_for('user.login'))
    return render_template('usuarios/register.html', form=form)

@user_views.route("/login/", methods=['GET', 'POST'])
def login():
    if 'id' in session:
        return redirect(url_for('home.home'))
    else:
        form = LoginForm()
        if form.validate_on_submit():
            correoE = form.correoE.data
            contrasenia = form.contrasenia.data
            user = Usuario.obtener_por_pass(correoE, contrasenia)
            if not user:
                flash('Verifica tus datos')
            else:
                session['id'] = user.id
                session['nombre'] = user.nombre
                session['aPaterno'] = user.aPaterno
                session['aMaterno'] = user.aMaterno
                session['correoE'] = user.correoE
                session['rol'] = user.rol
                return redirect(url_for('home.home'))
        return render_template('usuarios/Login.html', form=form)
    

@user_views.route("/home/mytaller/")
@user_views.route("/home/mytaller/<int:page>", methods=['GET'])
def mytaller(page=1):
    if session.get('rol') != 3:
        limit = 2
        total_talleresa = 0
        total_talleres = 0
        if session.get('rol') == 1:
            correoE = session.get('correoE')
            talleresm = Toma.get_talleres_by_correo(correoE, limit=2, page=page)
            tallerest = Toma.get_toma_by_correo(correoE)
            if tallerest:
                for tal in tallerest:
                    total_talleresa +=1
            pagess = math.ceil(total_talleresa / limit)
            return render_template('usuarios/talleres.html', talleres=talleresm, pages=pagess)
        
        elif session.get('rol') == 2:
            talleresp = Asignado.get_talleres_by_correo(session.get('correoE'), limit=2, page=page)
            talleres = Asignado.get_asign_by_correo(session.get('correoE'))
            if talleres:
                for tal in talleres:
                    total_talleres +=1
            pages = math.ceil(total_talleres / limit)
            return render_template('usuarios/talleres.html', talleres=talleresp, pages=pages)
        else:
            abort(401)
    else:
        abort(401)

@user_views.route("/home/mytaller/solicitar_taller/", methods=['POST', 'GET'])
def validinfo():
    if session.get('rol') != 3:
        if session.get('rol') == 2 or session.get('rol') == 1:
            form = ElegirTaller()
            tal = Taller.get_all_tal()

            talleres = [(-1, '')]
            for tall in tal:
                talleres.append((tall.id, tall.nombre))
            form.taller_id.choices = talleres
            if form.validate_on_submit():
                correoE = form.correoE.data
                taller_id = form.taller_id.data
                contrasenia = form.contrasenia.data
                if taller_id == -1:
                    flash('Debes seleccionar un taller')
                else:
                    if correoE == session.get('correoE'):
                        user = Usuario.obtener_por_pass(correoE, contrasenia)
                        if user:
                            tal = Toma.validar_inscrip(user.id, taller_id)
                            if tal is None:
                                Toma.solicitar_taller(user.id, taller_id)
                                flash('Solicitud enviada al administrador')
                            else:
                                flash('Ya estas inscrito en este taller o ya lo solicitaste anteriormente')
                        else:
                            flash('Contraseña incorrecta')
                    else:
                        flash('Verifica tu correo electrónico')

            return render_template('usuarios/validform.html', form=form)
        else:
            abort(401)
    else:
        abort(401)

@user_views.route("/home/mytaller/solicitar_impartir/", methods=['POST', 'GET'])
def solicitar_impartir():
    if session.get('rol') != 3:
        if session.get('rol') == 2 or session.get('rol') == 1:
            form = ElegirTaller()
            tal = Taller.get_all_tal()

            talleres = [(-1, '')]
            for tall in tal:
                talleres.append((tall.id, tall.nombre))
            form.taller_id.choices = talleres
            if form.validate_on_submit():
                correoE = form.correoE.data
                taller_id = form.taller_id.data
                contrasenia = form.contrasenia.data
                if taller_id == -1:
                    flash('Debes seleccionar un taller')
                else:
                    if correoE == session.get('correoE'):
                        user = Usuario.obtener_por_pass(correoE, contrasenia)
                        if user:
                            tal = Taller.get_talleres_by_prof(user.id, taller_id)
                            valid = Asignado.verificar_asign(taller_id)
                            if tal is None:
                                if valid != None:
                                    Asignado.solicitar_asign(user.id, taller_id)
                                    flash('Solicitud enviada al administrador')
                                else:
                                    flash('Este taller ya ha sido solicitado o ya esta ocupado. Consultalo con el administrador')
                            else:
                                flash('Ya estas inscrito en este taller o ya lo solicitaste anteriormente')
                        else:
                            flash('Contraseña incorrecta')
                    else:
                        flash('Verifica tu correo electrónico')

            return render_template('usuarios/validform.html', form=form)
        else:
            abort(401)
    else:
        abort(401)

@user_views.route("/home/olvide_contraseña/", methods=['POST', 'GET'])
def olvidcontra():
    form = OlvideContra()

    if form.validate_on_submit():
        nombre = form.nombre.data
        aPaterno = form.aPaterno.data
        aMaterno = form.aMaterno.data
        correoE = form.correoE.data
        telefono = form.telefono.data
        contrasenia = form.contrasenia.data

        user = Usuario.olvidcontra(nombre, aPaterno, aMaterno, correoE, telefono)
        if user is None:
            flash('Datos erroneos')
        else:
            user.contrasenia = contrasenia
            user.cambio_c()

            flash('Se cambió la contraseña')

    return render_template('usuarios/olvidecontra.html', form=form)

@user_views.route("/home/mi_perfil/", methods=['POST', 'GET'])
def my_profile():
    if session.get('id'):
        form = ProfileForm()
        user = Usuario.get_usu_by_correo(session.get('correoE'))

        if form.validate_on_submit():
            contrasenia = form.contrasenia.data 
            user.contrasenia = contrasenia
            user.cambio_c()
            flash('Se cambio tu contraseña')

        return render_template('usuarios/profile.html', form=form, user=user)
    else:
        abort(404)


@user_views.route("/logout/")
def logout():
    session.clear()
    return redirect(url_for('home.home'))

app/templates/usuarios/Login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock %}

{% block content %}
<!--Alertas-->

<!----------->
    <!---->
<div class="hero">
    <div class="container_login">
        <div class="formation">
            <div class="info_childs">
                <h2>Iniciar Sesión</h2>
                <p>
                </p>
            </div>
        </div>
        <div class="form_formation">
            <div class="form_information_ch">
                <h2>Inicio de Sesión</h2>
                <form class="form" method="POST">
                    {{ form.csrf_token }}
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <label>
                        <i class='bx bx-envelope'></i>
                        {{ form.correoE(autocomplete="off", placeholder="Correo electrónico") }}
                        {% if form.correoE.errors %}
                            {% for error in form.correoE.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bx-lock'></i>
                        {{ form.contrasenia(autocomplete="off", placeholder="Contraseña") }}
                        {% if form.contrasenia.errors %}
                            {% for error in form.contrasenia.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    {{ form.submit() }}
                </form>
                {% with messages = get_flashed_messages() %}
                    {% if messages%}
                        {% for message in messages %}
                            <div class="alert-log">
                                <p>{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <br>
                <a href="{{ url_for('user.olvidcontra') }}" class="link_form">Olvide mi contraseña</a>
                <p class="text_form">¿No tienes cuenta?</p>
                <a href="{{ url_for('user.register') }}" class="link_form">Registrate</a>
            </div>
        </div>
    </div>
</div>
    <!--<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>-->
{% endblock %}

app/templates/usuarios/olvidecontra.html
{% extends 'base.html' %}

{% block title %}
    Verificando
{% endblock %}

{% block content %}
<style>
    footer{
        margin-top: 50px;
    }
  </style>
    <h1 class="h1_rc"></h1>

    <div class="container_rc">
        <h2 class="h2_rc">Recuperar contraseña</h2>
        <form class="form_rc" method="POST">
            {{ form.csrf_token }}
            <div class="form_correo">
                {{ form.nombre.label }}
                {{ form.nombre(autocomplete="off", placeholder="Ej. Juan", class="correo_rc") }}
                {% if form.nombre.errors %}
                    {% for error in form.nombre.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.aPaterno.label }}
                {{ form.aPaterno(autocomplete="off", placeholder="Ej. Perez", class="correo_rc") }}
                {% if form.aPaterno.errors %}
                    {% for error in form.aPaterno.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.aMaterno.label }}
                {{ form.aMaterno(autocomplete="off", placeholder="Ej. Lopez", class="correo_rc") }}
                {% if form.aMaterno.errors %}
                    {% for error in form.aMaterno.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.correoE.label }}
                {{ form.correoE(autocomplete="off", placeholder="Ej. ejemplo@gmail.com", class="correo_rc") }}
                {% if form.correoE.errors %}
                    {% for error in form.correoE.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.telefono.label }}
                {{ form.telefono(autocomplete="off", placeholder="000-000-0000",class="correo_rc") }}
                {% if form.telefono.errors %}
                    {% for error in form.telefono.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.contrasenia.label }}
                {{ form.contrasenia(autocomplete="off", placeholder="**********", class="correo_rc") }}
                {% if form.contrasenia.errors %}
                    {% for error in form.contrasenia.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="rc_buttom">
                <a class="salir" href="{{ url_for('home.home') }}">Regresar</a>
                {{ form.submit(class="enviar_rc") }}
            </div>
            {% with messages = get_flashed_messages() %}
                    {% if messages%}
                        {% for message in messages %}
                            <div class="alert-log">
                                <p>{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
            {% endwith %}
        </form>
    </div>
{% endblock %}

app/templates/usuarios/profile.html
{% extends 'base.html' %}

{% block title %}
    Perfil de usuario
{% endblock %}

{% block content %}
<style>
    footer{
        margin-top: 100px;
    }
</style>
  <br>
  <br>
    <div class="data-print center">
        <div class="left row-padding">
            <center><h1 class="h1">Perfil de usuario</h1></center>
            <br>
            <form class="cbp-mc-form" method="POST">
                {{ form.csrf_token }}
                    <div class="cbp-mc-column h4">
                        <br>
                        <br>
                       Nombre completo: {{ user.nombre }} {{ user.aPaterno }} {{ user.aMaterno }}
                       <br>
                       <br>
                       Correo electrónico: {{ user.correoE }}
                       <br>
                       <br>
                       Número de teléfono: {{ user.telefono }}
                       <br>
                       <br>
                       Edad: {{ user.edad }}
                       <br>
                       <br>
                       {% if 'id' in session %}
                            {% if session['rol'] == 3 %}
                                <a href="{{ url_for('admin.update_data') }}">Editar mi información</a>                    
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="cbp-mc-column h4">
                        <br>
                        <br>
                    </div>
                    <div class="cbp-mc-column">
                        {{ form.contrasenia.label }}
                        {{ form.contrasenia(autocomplete="off") }}
                        {% if form.contrasenia.errors %}
                            {% for error in form.contrasenia.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                        {{ form.contrasenia_confirm.label }}
                        {{ form.contrasenia_confirm(autocomplete="off") }}
                        {% if form.contrasenia_confirm.errors %}
                            {% for error in form.contrasenia_confirm.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                        <div class="cbp-mc-submit-wrap">
                            {{ form.submit(class="cbp-mc-submit") }}
                        </div>
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/usuarios/register.html
{% extends 'base.html' %}
{% block title %}
    Registrate
{% endblock %}

{% block content %}
<style>
    footer{
        margin-top: 850px;
    }
</style>
<div class="hero">
    <div class="container_register">
        <div class="formation">
            <div class="info_childs">
                <h2>Bienvenido</h2>
                <p>Para poder inscribirte a un taller
                    antes necesitas crear una cuenta llenando
                    los espacios con la informacion que se pide
                </p>
            </div>
        </div>
        <div class="form_formation">
            <div class="form_information_ch">
                <h2>Crea una cuenta</h2>
                <form class="form" method="post">
                    {{ form.csrf_token }}
                    <label>
                        <i class='bx bx-user'></i>
                        {{ form.nombre(autocomplete="off", placeholder="Nombre(s)") }}
                        {% if form.nombre.errors %}
                            {% for error in form.nombre.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bx-user'></i>
                        {{ form.aPaterno(autocomplete="off", placeholder="Apellido paterno") }}
                        {% if form.aPaterno.errors %}
                            {% for error in form.aPaterno.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bx-user'></i>
                        {{ form.aMaterno(autocomplete="off", placeholder="Apellido materno") }}
                        {% if form.aMaterno.errors %}
                            {% for error in form.aMaterno.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bx-envelope'></i>
                        {{ form.correoE(autocomplete="off", placeholder="Correo electrónico") }}
                        {% if form.correoE.errors %}
                            {% for error in form.correoE.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bx-lock'></i>
                        {{ form.contrasenia(autocomplete="off", placeholder="Contraseña") }}
                        {% if form.contrasenia.errors %}
                            {% for error in form.contrasenia.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bxs-lock'></i>
                        {{ form.contrasenia_confirm(autocomplete="off", placeholder="Confirma tu contraseña") }}
                        {% if form.contrasenia_confirm.errors %}
                            {% for error in form.contrasenia_confirm.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        <i class='bx bxs-phone'></i>
                        {{ form.telefono(autocomplete="off", placeholder="Telefono celular") }}
                        {% if form.telefono.errors %}
                            {% for error in form.telefono.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        {{ form.edad.label }}
                        {{ form.edad() }}
                        {% if form.edad.errors %}
                            {% for error in form.edad.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    <label>
                        {{ form.rol.label }}
                        {{ form.rol() }}
                        {% if form.rol.errors %}
                            {% for error in form.rol.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </label>
                    {{ form.submit() }}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/usuarios/talleres.html
{% extends 'base.html' %}

{% block title %}
    Talleres
{% endblock %}

{% block content %}
<style>
    body{
        background-image: url(../../static/images/fondo.jpg);
        background-size: cover;
    }
    footer{
        margin-top: 100px;
    }
</style>
<div class="body">
{% if talleres %}
    {% for taller in talleres %}
        <div class="slide-container">
            <div class="slide-content">
                <div class="card-wrapper">
                    <div class="card">
                        <div class="image-content">
                            <span class="overlay"></span>
                            <div class="card-image">
                                <img src="{{ url_for('static', filename='/images/logo-1.png') }}" alt="" class="card-img">
                            </div>
                        </div>
                        <div class="card-content">
                            <h2 class="nombre">{{ taller.nombre_taller }}</h2>
                            <p class="descrip">
                                {{ taller.descrip_taller }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="slide-container">
        <div class="slide-content">
            <div class="card-wrapper">
                <div class="card">
                    <div class="image-content">
                        <span class="overlay"></span>
                        <div class="card-image">
                            <img src="{{ url_for('static', filename='/images/bx-plus-circle.svg') }}" alt="" class="card-img">
                        </div>
                    </div>
                    <div class="card-content">
                        {% if session['rol']==2 %} 
                            <a href="{{ url_for('user.solicitar_impartir') }}"><button class="inscripcion">Impartir taller</button></a>
                        {% else %}
                            <a href="{{ url_for('user.validinfo') }}"><button class="inscripcion">Inscribirme a taller</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="slide-container">
        <div class="slide-content">
            <div class="card-wrapper">
                <div class="card">
                    <div class="image-content">
                        <span class="overlay"></span>
                        <div class="card-image">
                            <img src="{{ url_for('static', filename='/images/bx-plus-circle.svg') }}" alt="" class="card-img">
                        </div>
                    </div>
                    <div class="card-content">
                        {% if session['rol']==2 %} 
                            <a href="{{ url_for('user.solicitar_impartir') }}"><button class="inscripcion">Impartir taller</button></a>
                        {% else %}
                            <a href="{{ url_for('user.validinfo') }}"><button class="inscripcion">Inscribirme a taller</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
</div>
<div class="body" style="min-height: 0;">
{% if pages %} 
        <div class="numpages">
          {% for i in range(pages) %}
            <a href="{{ url_for('user.mytaller', page=(i + 1)) }}">{{ i + 1 }}</a>
          {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

app/templates/usuarios/validform.html
{% extends 'base.html' %}

{% block title %}
    Verificando
{% endblock %}

{% block content %}
<style>
    footer{
        margin-top: 50px;
    }
</style>
    <h1 class="h1_rc"></h1> <!--Importante no quitar-->
    <div class="container_rc">
        {% if session['rol'] == 1 %}
            <h2 class="h2_rc">Solicitud de inscripción a taller</h2>
        {% else %}            
            <h2 class="h2_rc">Solicitud para impartir taller</h2>
        {% endif %}

        <form class="form_rc" method="POST">
            {{ form.csrf_token }}
            <div class="form_correo">
                {{ form.correoE.label }}
                {{ form.correoE(autocomplete="off", placeholder="Correo electronico", class="correo_rc") }}
                {% if form.contrasenia.errors %}
                    {% for error in form.contrasenia.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.taller_id.label }}
                {{ form.taller_id(class="correo_rc") }}
                {% if form.taller_id.errors %}
                    {% for error in form.taller_id.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.contrasenia.label }}
                {{ form.contrasenia(autocomplete="off", placeholder="**********", class="correo_rc") }}
                {% if form.contrasenia.errors %}
                    {% for error in form.contrasenia.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endif %}
                {% with messages = get_flashed_messages() %}
                    {% if messages%}
                        {% for message in messages %}
                            <div class="alert-log">
                                <p>{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            <div class="rc_buttom">
                <a class="salir" href="{{ url_for('home.home') }}">Regresar</a>
                {{ form.submit(class="enviar_rc") }}
            </div>
        </form>
    </div>
{% endblock %}