app/views/home_views.py
from flask import Blueprint, render_template, abort

from models.talleres import Taller

home_views = Blueprint('home', __name__)

@home_views.route("/")
@home_views.route("/home/")
def home():
    return render_template('home/home.html')

@home_views.route("/home/info_texcalac")
def info_texcalac():
    return render_template('home/infoTexca.html')

@home_views.route("/home/info_talleres")
@home_views.route("/home/info_talleres/<int:page>", methods=['GET'])
def info_talleres(page=1):
    limit = 5
    talleres = Taller.get_all(limit=limit, page=page)
    if talleres is None: abort(404)
    return render_template('home/infotalleres.html', talleres=talleres, page=page)

app/views/users_views.py
from flask import Blueprint, redirect, render_template, url_for, flash, abort, session

from models.usuarios import Usuario, Toma

from models.talleres import Taller, Asignado

from forms.usuarios_forms import LoginForm, RegisterForm, ElegirTaller, OlvideContra, ProfileForm

import datetime
import math


user_views = Blueprint('user', __name__)

@user_views.route("/register/", methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        nombre = form.nombre.data
        aPaterno = form.aPaterno.data
        aMaterno = form.aMaterno.data
        correoE = form.correoE.data
        contrasenia = form.contrasenia.data
        telefono = form.telefono.data
        edad = form.edad.data
        rol = form.rol.data
        fecha_actual = datetime.datetime.now().date()

        user = Usuario(nombre, aPaterno, aMaterno, correoE, contrasenia, telefono, edad, rol, None, fecha_actual)
        user.guardar()
        return redirect(url_for('user.login'))
    return render_template('usuarios/register.html', form=form)

@user_views.route("/login/", methods=['GET', 'POST'])
def login():
    if 'id' in session:
        return redirect(url_for('home.home'))
    else:
        form = LoginForm()
        if form.validate_on_submit():
            correoE = form.correoE.data
            contrasenia = form.contrasenia.data
            user = Usuario.obtener_por_pass(correoE, contrasenia)
            if not user:
                flash('Verifica tus datos')
            else:
                session['id'] = user.id
                session['nombre'] = user.nombre
                session['aPaterno'] = user.aPaterno
                session['aMaterno'] = user.aMaterno
                session['correoE'] = user.correoE
                session['rol'] = user.rol
                return redirect(url_for('home.home'))
        return render_template('usuarios/Login.html', form=form)
    

@user_views.route("/home/mytaller/")
@user_views.route("/home/mytaller/<int:page>", methods=['GET'])
def mytaller(page=1):
    if session.get('rol') != 3:
        limit = 2
        total_talleresa = 0
        total_talleres = 0
        if session.get('rol') == 1:
            correoE = session.get('correoE')
            talleresm = Toma.get_talleres_by_correo(correoE, limit=2, page=page)
            tallerest = Toma.get_toma_by_correo(correoE)
            if tallerest:
                for tal in tallerest:
                    total_talleresa +=1
            pagess = math.ceil(total_talleresa / limit)
            return render_template('usuarios/talleres.html', talleres=talleresm, pages=pagess)
        
        elif session.get('rol') == 2:
            talleresp = Asignado.get_talleres_by_correo(session.get('correoE'), limit=2, page=page)
            talleres = Asignado.get_asign_by_correo(session.get('correoE'))
            if talleres:
                for tal in talleres:
                    total_talleres +=1
            pages = math.ceil(total_talleres / limit)
            return render_template('usuarios/talleres.html', talleres=talleresp, pages=pages)
        else:
            abort(401)
    else:
        abort(401)

@user_views.route("/home/mytaller/solicitar_taller/", methods=['POST', 'GET'])
def validinfo():
    if session.get('rol') != 3:
        if session.get('rol') == 2 or session.get('rol') == 1:
            form = ElegirTaller()
            tal = Taller.get_all_tal()

            talleres = [(-1, '')]
            for tall in tal:
                talleres.append((tall.id, tall.nombre))
            form.taller_id.choices = talleres
            if form.validate_on_submit():
                correoE = form.correoE.data
                taller_id = form.taller_id.data
                contrasenia = form.contrasenia.data
                if taller_id == -1:
                    flash('Debes seleccionar un taller')
                else:
                    if correoE == session.get('correoE'):
                        user = Usuario.obtener_por_pass(correoE, contrasenia)
                        if user:
                            tal = Toma.validar_inscrip(user.id, taller_id)
                            if tal is None:
                                Toma.solicitar_taller(user.id, taller_id)
                                flash('Solicitud enviada al administrador')
                            else:
                                flash('Ya estas inscrito en este taller o ya lo solicitaste anteriormente')
                        else:
                            flash('Contraseña incorrecta')
                    else:
                        flash('Verifica tu correo electrónico')

            return render_template('usuarios/validform.html', form=form)
        else:
            abort(401)
    else:
        abort(401)

@user_views.route("/home/mytaller/solicitar_impartir/", methods=['POST', 'GET'])
def solicitar_impartir():
    if session.get('rol') != 3:
        if session.get('rol') == 2 or session.get('rol') == 1:
            form = ElegirTaller()
            tal = Taller.get_all_tal()

            talleres = [(-1, '')]
            for tall in tal:
                talleres.append((tall.id, tall.nombre))
            form.taller_id.choices = talleres
            if form.validate_on_submit():
                correoE = form.correoE.data
                taller_id = form.taller_id.data
                contrasenia = form.contrasenia.data
                if taller_id == -1:
                    flash('Debes seleccionar un taller')
                else:
                    if correoE == session.get('correoE'):
                        user = Usuario.obtener_por_pass(correoE, contrasenia)
                        if user:
                            tal = Taller.get_talleres_by_prof(user.id, taller_id)
                            valid = Asignado.verificar_asign(taller_id)
                            if tal is None:
                                if valid != None:
                                    Asignado.solicitar_asign(user.id, taller_id)
                                    flash('Solicitud enviada al administrador')
                                else:
                                    flash('Este taller ya ha sido solicitado o ya esta ocupado. Consultalo con el administrador')
                            else:
                                flash('Ya estas inscrito en este taller o ya lo solicitaste anteriormente')
                        else:
                            flash('Contraseña incorrecta')
                    else:
                        flash('Verifica tu correo electrónico')

            return render_template('usuarios/validform.html', form=form)
        else:
            abort(401)
    else:
        abort(401)

@user_views.route("/home/olvide_contraseña/", methods=['POST', 'GET'])
def olvidcontra():
    form = OlvideContra()

    if form.validate_on_submit():
        nombre = form.nombre.data
        aPaterno = form.aPaterno.data
        aMaterno = form.aMaterno.data
        correoE = form.correoE.data
        telefono = form.telefono.data
        contrasenia = form.contrasenia.data

        user = Usuario.olvidcontra(nombre, aPaterno, aMaterno, correoE, telefono)
        if user is None:
            flash('Datos erroneos')
        else:
            user.contrasenia = contrasenia
            user.cambio_c()

            flash('Se cambió la contraseña')

    return render_template('usuarios/olvidecontra.html', form=form)

@user_views.route("/home/mi_perfil/", methods=['POST', 'GET'])
def my_profile():
    if session.get('id'):
        form = ProfileForm()
        user = Usuario.get_usu_by_correo(session.get('correoE'))

        if form.validate_on_submit():
            contrasenia = form.contrasenia.data 
            user.contrasenia = contrasenia
            user.cambio_c()
            flash('Se cambio tu contraseña')

        return render_template('usuarios/profile.html', form=form, user=user)
    else:
        abort(404)


@user_views.route("/logout/")
def logout():
    session.clear()
    return redirect(url_for('home.home'))

app/templates/Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio CDC</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <section>
        <div class="form-box">
            <div class="form_value">
                {% with messages = get_flashed_messages() %}
                    {% if messages%}
                        {% for message in messages %}
                            <h2>{{ message }}</h2>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <form action="/login" method="POST">
                    {{ form.csrf_token }}
                    <h2>Inicio de Sesión</h2>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
                        {{ form.correoE.label }}
                        {{ form.correoE(class="entrada") }}
                        {% if form.correoE.errors %}
                            {% for error in form.correoE.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        {{ form.contrasenia.label }}
                        {{ form.contrasenia(class="entrada") }}
                        {% if form.contrasenia.errors %}
                            {% for error in form.contrasenia.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="forget">
                        <label for=""><a href="">Olvide mi Contraseña</a></label>
                    </div>
                    {{ form.submit(class="btn") }}
                    <div class="registro">
                        <p>No tienes una cuenta? </p>
                        <a href="">Registrate</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/logo_bln.png') }}">
    <!--Estilos-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nvar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/alerts.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">
    <!--Enlaces-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!--Scripts-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/nav.js') }}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header class="nvbar">
        <div class="logo">
            <a href="{{ url_for('home.home') }}"><img src="{{ url_for('static', filename='images/logo_bln.png') }}" alt="Logo_cdc"></a>
        </div>
        <nav>
            <ul class="nav_links">
                <li><a href="{{ url_for('home.home') }}">Inicio</a></li>
                <li><a href="https://goo.gl/maps/odsUZ2KrJsEKM49NA">Encuentranos</a></li>
                <li><a href="{{ url_for('home.info_texcalac') }}">¿Sabias que?</a></li>
                <li><a href="{{ url_for('home.info_talleres') }}">Nuestros talleres</a></li>
                {% if 'id' in session %}
                    <li><a href="{{ url_for('user.logout') }}">Cerrar sesión</a></li>
                </ul>
            </nav>
            <a href="{{ url_for('user.my_profile') }}" class="btn"><button>{{ session['nombre'] }}</button></a>
                {% else %}
                    <li><a href="{{ url_for('user.register') }}">Registrarme</a></li>
                </ul>
            </nav>
            <a href="{{ url_for('user.login') }}" class="btn"><button>Iniciar sesión</button></a>
                {% endif %}
        <!--Esta parte es del script-->
        <a onclick="openNav()" class="menu" href="#"><button>{% if 'id' in session %} {{ session['nombre'] }}</button></a>
        {% else %}Menu</button></a>{% endif %} 
        
        <div class="overlay" id="menu_rt">
            <a onclick="closeNav()" class="close">&times;</a>
            <div class="overlay_content">
                {% if 'id' in session %}
                    <a href="{{ url_for('user.logout') }}">Cerrar sesión</a>
                </ul>
                {% else %}
                    <a href="{{ url_for('user.login') }}">Iniciar sesión</a>
                    <a href="{{ url_for('user.register') }}">Registrarme</a>
                {% endif %}
                <a href="{{ url_for('home.info_talleres') }}">Nuestros talleres</a>
                <a href="https://goo.gl/maps/odsUZ2KrJsEKM49NA">Encuentranos</a>
                <a href="{{ url_for('home.info_texcalac') }}">¿Sabias que?</a>
                <a href="https://www.facebook.com/texcalacunido">Facebook</a>
            </div>
        </div>
    </header>
        {% block content %}
        
        {% endblock %}
    <footer>
        <div class="footer_contenido">
            <h3>CDC</h3>
            <p>
                Todos los derechos son reservados ajenos a cualquier 
                partido político 
            </p>
            <ul class="iconosS">
                <li><a href=""><i class='bx bx-envelope'></i></a></li>
                <li><a href="https://www.facebook.com/texcalacunido"><i class='bx bxl-facebook' ></i></a></li>
                <li><a href=""><i class='bx bxl-instagram' ></i></a></li>
            </ul>
            <br>
            <a style="text-decoration: none; color: white;" href="{{ url_for('static', filename='pdf/Manual_De_Usuario.pdf') }}"><i class='bx bxl-pdf'></i>¿Necesitas ayuda para usar el sitio web? Clic aquí</a>
            <br>
            <a style="text-decoration: none; color: white;" href="{{ url_for('static', filename='pdf/Terminos_y_condiciones_Usuario.pdf') }}"><i class='bx bxl-pdf'></i>Términos y condiciones</a>
            <br>
        </div>
        <div class="footer_dr">
            <p>Copyright &copy; 2023 Centro de Desarrollo Comunitario. designed by <span>PayCorp</span></p>
        </div>
    </footer>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>